#settings
is_debug: True
# dataset
data_path: './data/local_data_structure'
path_to_test_x: "./data/test_data_structure"
input_len: 12
label_len: 3
output_len: 3
encoder_var_len: 3
decoder_var_len: 1
capacity: 1

# Model
model:
  hidden_dims: 128
  nhead: 8
  dropout: 0
  encoder_layers: 2
  decoder_layers: 1
# trainning
train_cars: 13
var_cars: 2
num_workers: 10
train_epochs: 100
batch_size: 64
patience: 5
lr: 0.00003
lr_adjust: 'type1'
checkpoints: './checkpoints'

loss:
  name: "MSELoss"
gpu:
  0